"""
Train the EfficientNet classifier on the hand-drawn-style dataset in
training_testing_datasets/Training/training_DL.

Builds (image_path, master_key) pairs by mapping each training_DL/<name>/
folder to its category-qualified key (e.g. apron-6 -> Aprons/apron-6, looked
up from the master catalog), then adds synthetic sketches from training_synth/
(generate with scripts/generate_synthetic_sketches.py), the master seed PNGs
and any feedback corrections. Every image is mirror-doubled: it trains its own
class and, horizontally flipped, its -mirror class.

Trains a fresh ImageNet backbone each run (fine-tuning from previous versioned
weights was a trap — it locked in the old model's biases), saves versioned
weights + label_index in the same format the server hot-loads.

Run from backend/:  ./.venv/bin/python scripts/train_from_dl.py
"""
from __future__ import annotations

import json
import logging
from collections import Counter
from pathlib import Path

import torch
import torch.nn as nn
from torchvision import transforms

from app.features.classifier.efficientnet import _build_model
from app.features.vision.sketch_preprocessor import preprocess_sketch

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("train_from_dl")

ROOT = Path(__file__).resolve().parents[2]
DATASETS = ROOT / "training_testing_datasets" / "Training"
MASTERS = DATASETS / "Encore_master_drawings"
DL = DATASETS / "training_DL"
SYNTH = DATASETS / "training_synth"  # generated by scripts/generate_synthetic_sketches.py
FEEDBACK = ROOT / "training_testing_datasets" / "feedback"
MODEL_DIR = ROOT / "backend" / "data" / "models"
EPOCHS = 20
BATCH = 32

# Strong augmentation — this recipe (plus mirror-doubling below) took the client
# test set from 24% to 48%+ top-1. Never add RandomHorizontalFlip here: flips are
# applied deliberately with the "-mirror" label instead.
_TRAIN_TF = transforms.Compose([
    transforms.Grayscale(num_output_channels=3),
    transforms.Resize((248, 248)),
    transforms.RandomAffine(degrees=8, translate=(0.06, 0.06), scale=(0.82, 1.18), shear=6, fill=255),
    transforms.RandomPerspective(distortion_scale=0.22, p=0.5, fill=255),
    transforms.RandomResizedCrop(224, scale=(0.75, 1.0), ratio=(0.8, 1.25)),
    transforms.ColorJitter(brightness=0.3, contrast=0.3),
    transforms.RandomApply([transforms.GaussianBlur(3)], p=0.25),
    transforms.ToTensor(),
    transforms.RandomErasing(p=0.25, scale=(0.02, 0.08)),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])


def _mirror_of(key: str) -> str:
    return key[:-7] if key.endswith("-mirror") else key + "-mirror"


class _MirrorDoubledDataset(torch.utils.data.Dataset):
    """Every image trains its own class AND (h-flipped) its -mirror class."""

    def __init__(self, items: list[tuple[Path, str]], key_to_idx: dict[str, int]):
        self.rows: list[tuple[Path, int, bool]] = []
        for p, k in items:
            if k in key_to_idx:
                self.rows.append((p, key_to_idx[k], False))
            mk = _mirror_of(k)
            if mk in key_to_idx:
                self.rows.append((p, key_to_idx[mk], True))

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int):
        path, label, flip = self.rows[idx]
        img = preprocess_sketch(path).convert("RGB")
        if flip:
            img = img.transpose(0)  # PIL FLIP_LEFT_RIGHT
        return _TRAIN_TF(img), label


def stem_to_key() -> dict[str, str]:
    """map base drawing stem (e.g. 'apron-6') -> 'Aprons/apron-6'."""
    m: dict[str, str] = {}
    for cat in sorted(MASTERS.iterdir()):
        if not cat.is_dir():
            continue
        for png in cat.glob("*.png"):
            if png.stem.endswith("-mirror"):
                continue
            m[png.stem] = f"{cat.name}/{png.stem}"
    return m


def collect() -> list[tuple[Path, str]]:
    lut = stem_to_key()
    items: list[tuple[Path, str]] = []

    # 1) training_DL images (real apron photos + generated sketches)
    for folder in sorted(DL.iterdir()):
        if not folder.is_dir() or folder.name not in lut:
            continue
        key = lut[folder.name]
        imgs = [p for p in folder.iterdir()
                if p.suffix.lower() in {".jpg", ".jpeg", ".png"} and not p.name.startswith(".")]
        items += [(p, key) for p in imgs]

    # 1b) synthetic sketches rendered from master geometry (training_synth/<Cat>/<stem>/)
    if SYNTH.exists():
        for cat_dir in sorted(SYNTH.iterdir()):
            if not cat_dir.is_dir():
                continue
            for stem_dir in sorted(cat_dir.iterdir()):
                if not stem_dir.is_dir():
                    continue
                key = f"{cat_dir.name}/{stem_dir.name}"
                items += [(p, key) for p in sorted(stem_dir.glob("*.png"))]

    # 2) master seed PNGs (base + mirror) so every class is represented
    for cat in sorted(MASTERS.iterdir()):
        if not cat.is_dir():
            continue
        for png in cat.glob("*.png"):
            items.append((png, f"{cat.name}/{png.stem}"))

    # 3) feedback corrections
    manifest = FEEDBACK / "manifest.jsonl"
    if manifest.exists():
        for line in manifest.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
                rel, key = e.get("image_path", ""), e.get("master_key", "")
                p = FEEDBACK / rel
                if rel and key and p.exists():
                    items.append((p, key))
            except Exception:
                continue
    return items


def main() -> None:
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    log.info("device = %s", device)

    items = collect()
    counts = Counter(k for _, k in items)
    log.info("Collected %d images across %d classes", len(items), len(counts))

    # label index = saved one (keeps class order stable with server)
    idx_path = MODEL_DIR / "label_index.json"
    label_index: list[str] = json.loads(idx_path.read_text())
    key_to_idx = {k: i for i, k in enumerate(label_index)}
    for k in sorted(counts):
        if k not in key_to_idx:
            label_index.append(k)
            key_to_idx[k] = len(label_index) - 1
    n_classes = len(label_index)
    log.info("label index has %d classes", n_classes)

    model = _build_model(n_classes)
    # extra dropout in the head + freeze the first 2 feature blocks (regularization
    # against the small real dataset; proven recipe on the client test set)
    model.classifier = nn.Sequential(nn.Dropout(0.4), nn.Linear(model.classifier[1].in_features, n_classes))
    for name, p in model.features.named_parameters():
        if name.startswith(("0.", "1.")):
            p.requires_grad = False
    pts = sorted(MODEL_DIR.glob("efficientnet_v*.pt"))
    model.to(device)

    ds = _MirrorDoubledDataset(items, key_to_idx)
    loader = torch.utils.data.DataLoader(ds, batch_size=BATCH, shuffle=True)
    log.info("training rows after mirror-doubling: %d", len(ds))
    opt = torch.optim.Adam(
        [p for p in model.parameters() if p.requires_grad], lr=1e-4, weight_decay=1e-4
    )
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=EPOCHS, eta_min=1e-6)
    crit = nn.CrossEntropyLoss(label_smoothing=0.1)

    model.train()
    for epoch in range(1, EPOCHS + 1):
        total, seen = 0.0, 0
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            opt.zero_grad()
            out = model(images)
            loss = crit(out, labels)
            loss.backward()
            opt.step()
            total += loss.item()
            seen += len(images)
        sched.step()
        log.info("epoch %2d/%d  loss=%.4f  (%d imgs)", epoch, EPOCHS, total / max(len(loader), 1), seen)

    next_v = len(pts) + 1
    out_path = MODEL_DIR / f"efficientnet_v{next_v:03d}.pt"
    model.to("cpu").eval()
    torch.save(model.state_dict(), out_path)
    idx_path.write_text(json.dumps(label_index))
    log.info("SAVED %s  (%d classes)", out_path.name, n_classes)


if __name__ == "__main__":
    main()
